-- Add profile fields to users table
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS college VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS branch VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS cgpa VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS graduation_year VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS linkedin_url VARCHAR;
ALTER TABLE users ADD COLUMN IF NOT EXISTS github_url VARCHAR;
